### ISSUE TITLE
Gnome 47 support

### ISSUE THREAD

**Issue by mariuszste** [t184256/gnome-shell-extension-autohide-volume#5]
It's me again, still loving it. Please update and publish a version for gnome 47

**Comment by t184256** [comment]
Which distro are you using that gets new GNOME so fast?

**Comment by mariuszste** [comment]
Arch

**Comment by t184256** [comment]
7514e33 submitted for review on extensions.gnome.org. Meanwhile, you can check it out and `gnome-extensions pack . --force --extra-source=LICENSE --extra-source=README.md && gnome-extensions install autohide-volume@unboiled.info.shell-extension.zip` to test locally.

**Comment by t184256** [comment]
... or not, it's been approved already
